sudo: required
services:
    - docker

before_install:
    - docker build -t vikalf/vicsites.web .

script:
    - echo good!!

#deploy:
#    edge: true
#    provider: elasticbeanstalk
#    region: "us-east-2"
#    app: "VicSites-Web"
#    env: "VicsitesWeb-env"
#    bucket_name: "elasticbeanstalk-us-east-2-238939573193"
#    bucket_path: "VicSites-Web"
#    on:
#        branch: master
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key: $AWS_SECRET_KEY